import Head from 'next/head'
import Image from 'next/image'
import Userpic from './../../public/profile2.jpg'
import {FaFacebook, FaInstagram, FaTwitter, FaLinkedin} from 'react-icons/fa'

export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className='main'>
        <div className='container'>
          <div className='wrapper'>
            <div className='about-text'>
              <span className='name'>Juliana Lobatto</span>
              <span className='description'>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Mauris magna libero, convallis et ante vel, vehicula elementum velit. Nunc est nisi, ornare vitae justo at, lobortis dapibus tortor. Vestibulum nec viverra sapien. Nunc sed dapibus mauris. Etiam commodo at eros ut lacinia. Sed imperdiet nec eros ut ultrices. Pellentesque sagittis neque nec magna pharetra tempor.</span>
              <div className='links'>
                <a href='#'><FaFacebook /></a>
                <a href='#'><FaInstagram /></a>
                <a href='#'><FaTwitter /></a>
                <a href='#'><FaLinkedin /></a>
              </div>
            </div>
            <Image 
              src={Userpic}
              width={300}
              height={300}
              alt=''
            />
          </div>
        </div>
      </main>
    </>
  )
}
